backend:
  name: github
  repo: Benaud12/gatsby-netlify-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - file: markdown/homepage.md
        label: Home Page
        name: index
        fields:
          - { label: Intro, name: intro, widget: markdown }
